### ISSUE TITLE
Site Navigation - Comic

### ISSUE THREAD

**Issue by SickSick6** [davidjeddy/pieces-compendium#1]
I would like to make it so you click on Comic and you have a thumbnail for each comic, the first one being Meat. You then can click through the pages, with the Next Page option still implemented but no thumbnail for page 2 on the main Comic page. You just click on Meat and it defaults to page 1. I think the whole keeping track of what page you last left off on is back burner & not as important at this point. More important is the UI & feel of the navigation of the site. I would like to still be able to post them as Articles but as far as the user knows, they just click Comic, then Meat and they're on page 1. or possibly a sub-section with each page as a thumbnail. But when clicking Comic they should land on a page that just has a thumbnail for each Comic, per character.

**Comment by davidjeddy** [comment]
Make a category called `Meat Story'.
Assign it to the 'Comic' category.
Assign the episodes to the 'Meat Story' category.

Exp:
top category > sub category > article
comic > meat story > ep1
comic > meat story > ep2
comic > meat story > ep3

**Comment by SickSick6** [comment]
Sounds good. I'd rather just call it "Meat" though. Meat Story sounds like
a porno. Can I make Categories? Thought I was only able to create Articles

**Comment by SickSick6** [comment]
So it um.. logs this email conversation in the github ticket.. good to
know. I'll keep it professional

**Comment by davidjeddy** [comment]
Correct, and yes feel free to call the child article-category to what you deem appropriate.

**Comment by davidjeddy** [comment]
This functionality is indeed not yet added. Reopening.

**Comment by davidjeddy** [comment]
Closing as no longer relevant, different solution resolved functionality need.
