### ISSUE TITLE
Landing page should be an article

### ISSUE THREAD

**Issue by davidjeddy** [davidjeddy/pieces-compendium#7]

**Comment by SickSick6** [comment]
No description?!?! Unacceptabllllllle!!!!
But yeah, the title says it all simple enough. Going back to the original format of the landing page being an article.

**Comment by davidjeddy** [comment]
Assumption is the most recent published article while keeping the title text.
\

**Comment by SickSick6** [comment]
Doesn't appear to have worked. The landing page is still a series of links, one of which now being Landing page. Maybe because we put it under the News category?

**Comment by davidjeddy** [comment]
Have not deployed changes yet. Attempting to verify changes will not cause issues.
